# Generated by Django 5.0.1 on 2024-02-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="product_id",
        ),
        migrations.AddField(
            model_name="category",
            name="product_id",
            field=models.ManyToManyField(to="auctions.list_item"),
        ),
    ]
