# Generated by Django 4.2.4 on 2023-10-23 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='list_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('imageUrl', models.CharField(max_length=1000)),
                ('active_status', models.BooleanField(default=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.list_items')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('product_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.list_items')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=50)),
                ('product_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.list_items')),
            ],
        ),
        migrations.CreateModel(
            name='bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_bid', models.IntegerField(max_length=1000)),
                ('last_bid', models.IntegerField(max_length=1000)),
                ('last_bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_bidder', to=settings.AUTH_USER_MODEL)),
                ('product_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.list_items')),
            ],
        ),
    ]
