# Generated by Django 4.2.4 on 2023-10-23 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_list_items_watchlist_comments_categories_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='default_bid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bid',
            name='last_bid',
            field=models.IntegerField(),
        ),
    ]
