# Generated by Django 4.2.4 on 2023-10-31 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_list_item_bid_alter_list_item_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_item',
            name='bid',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
        migrations.AlterField(
            model_name='list_item',
            name='comments',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.comment'),
        ),
        migrations.AlterField(
            model_name='list_item',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
