# Generated by Django 5.0.1 on 2024-02-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_remove_watchlist_id_alter_bid_last_bid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="last_bid",
            field=models.IntegerField(default=0),
        ),
    ]
