# Generated by Django 4.2.4 on 2023-10-31 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_list_item_bid_alter_list_item_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list_item',
            old_name='intialBid',
            new_name='initialBid',
        ),
    ]
