# Generated by Django 5.0.1 on 2024-02-04 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_bid_last_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="last_bidder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="last_bidder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
