# Generated by Django 4.2.4 on 2023-10-31 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_intialbid_list_item_initialbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_item',
            name='bid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
    ]
