# Generated by Django 4.2.4 on 2023-10-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_categories_product_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='default_bid',
            new_name='b_default_bid',
        ),
        migrations.RenameField(
            model_name='bid',
            old_name='product_title',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='product_title',
            new_name='C_product_id',
        ),
        migrations.RenameField(
            model_name='watchlist',
            old_name='product_title',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='product_title',
        ),
        migrations.AddField(
            model_name='comments',
            name='c_product_id',
            field=models.ManyToManyField(blank=True, to='auctions.list_items'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='category_title',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='list_items',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
