# Generated by Django 4.2.4 on 2023-10-31 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_list_item_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
