# Generated by Django 4.2.4 on 2023-10-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_default_bid_bid_b_default_bid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='b_default_bid',
            new_name='default_bid',
        ),
        migrations.RenameField(
            model_name='categories',
            old_name='C_product_id',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='c_product_id',
            new_name='product_id',
        ),
    ]
